# Generated by Django 2.2.24 on 2023-05-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='옵션명')),
                ('price', models.IntegerField(verbose_name='상품 가격')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_set', related_query_name='option', to='platform_app.Product', verbose_name='Product 테이블 외래키')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='platform_app.Tag', verbose_name='Tag:Product M:M 관계'),
        ),
    ]
